## Numpy Arrays

In [1]:
import numpy as np

In [2]:
sales = [0, 5, 155, 0, 518, 0, 1827, 616, 317, 325]

sales_array = np.array(sales)
sales_array

array([   0,    5,  155,    0,  518,    0, 1827,  616,  317,  325])

**Array Properties**

* ndim - show the number of dimensions(axes) in the array
* shape - show the size of the array for each dimension (unidimensional, bidimensional, tridimensional...)
* size - the total number of elements in the array
* dtype - show the data type of the elements in the array

In [3]:
print(f"ndim: {sales_array.ndim}")
print(f"shape: {sales_array.shape}")
print(f"size: {sales_array.size}")
print(f"dtype: {sales_array.dtype}")
# ndarray its a stand data type for n-dimensional array

ndim: 1
shape: (10,)
size: 10
dtype: int32


In [4]:
sales = [[0, 5, 155, 0, 518], [0, 1827, 616, 317, 325]]
sales_array = np.array(sales)
sales_array

array([[   0,    5,  155,    0,  518],
       [   0, 1827,  616,  317,  325]])

In [5]:
print(f"ndim: {sales_array.ndim}") # the sales_array has 2 dimensions
print(f"shape: {sales_array.shape}") # the first dimension has a size of 2 rows and the second a size of 5 columns
print(f"size: {sales_array.size}") # it has 10 elements total
print(f"dtype: {sales_array.dtype}") # the elements are stored as 64-bit integers

ndim: 2
shape: (2, 5)
size: 10
dtype: int32


**Another example**

In [6]:
np.array(range(5))

array([0, 1, 2, 3, 4])

In [7]:
array = np.array(range(5)) # one dimension array
array

array([0, 1, 2, 3, 4])

In [8]:
array_2d = np.array([range(5), range(5)]) # two dimensions array
array_2d

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

In [9]:
print(f"one dimension array shape = {array.shape}") # 5 columns and one single row
print(f"two dimensions array shape = {array_2d.shape}") # 2 rows and 5 columns

one dimension array shape = (5,)
two dimensions array shape = (2, 5)


In [10]:
print(f"one dimension array ndim = {array.ndim}")
print(f"two dimensions array ndim = {array_2d.ndim}")

one dimension array ndim = 1
two dimensions array ndim = 2


In [11]:
print(f"one dimnesion array dtype = {array.dtype}")
print(f"two dimension array dtype = {array_2d.dtype}")

one dimnesion array dtype = int32
two dimension array dtype = int32


In [12]:
print(f"one dimension array size = {array.size}") # 5 its the number of elements
print(f"two dimensions array size = {array_2d.size}") # 10 its the number of elements

one dimension array size = 5
two dimensions array size = 10
