## Array Operations

In [1]:
import numpy as np

In [2]:
rng = np.random.default_rng(123)

inventory = rng.integers(0, 100, 10)
inventory

array([ 1, 68, 59,  5, 90, 22, 25, 18, 33, 17], dtype=int64)

In [3]:
inventory - 24

array([-23,  44,  35, -19,  66,  -2,   1,  -6,   9,  -7], dtype=int64)

In [4]:
inventory / 2 #dtype = float

array([ 0.5, 34. , 29.5,  2.5, 45. , 11. , 12.5,  9. , 16.5,  8.5])

In [5]:
price = (rng.random(10) * 10).round(2)

price

array([8.12, 9.23, 2.77, 8.2 , 8.9 , 5.13, 2.45, 8.24, 2.14, 7.41])

In [6]:
(price * inventory).sum()

2160.21

In [7]:
inventory_list = list(inventory)
inventory_list

[1, 68, 59, 5, 90, 22, 25, 18, 33, 17]

In [8]:
new_inventory = []

for x in inventory_list:
    new_inventory.append(x*2)

new_inventory

[2, 136, 118, 10, 180, 44, 50, 36, 66, 34]