## Array Aggregation Methods

That aggregation methods let you calculate metrics like sum, mean, and max


In [1]:
import numpy as np

In [11]:
rng = np.random.default_rng(616)

numbers = rng.integers(0, 100, 10)
numbers

price = np.arange(10)
price

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
# mean
numbers.mean()

49.7

In [6]:
# sum
numbers.sum()

497

In [7]:
# max
numbers.max()

93

In [8]:
# min
numbers.min()

11

In [9]:
# desvio padrão
numbers.std()

23.195042573791497

In [17]:
my_array = (price * numbers)
my_array

array([  0,  39, 186, 258, 192, 230, 288, 210,  88, 513], dtype=int64)

In [21]:
price_2d = price.reshape(5, 2)
price_2d

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [23]:
price_2d.sum(axis=1)

array([ 1,  5,  9, 13, 17])