## Array Creation

As an alternative to corverting lists, we can create our arrays using some stand functions of numpy

In [1]:
import numpy as np

In [2]:
# the function ones create an array with rows and columns based in your dimensions, as long as we provide more then two dimensios 
# np.ones((rows, cols), dtype)
# by default the array will be created with float numbers, but if we use dtype=int this will be fixed
np.ones(4, ) # array([1., 1., 1., 1.])
np.ones((6,9), dtype=int)

array([[1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [3]:
# the function zeros create an array with zeros and has the same structure of the ones function.
np.zeros((2, 5), dtype=int)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [4]:
# the functions arange has the same funcionality of range function in python, then it create a numerical array, so dont need to convert it
# np.arange(start, stop, step) <- the same structure of range in python
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
# the function linspace
np.linspace(0, 100, 11)


array([  0.,  10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

In [6]:
# reshape
np.arange(1, 9, 2).reshape(2, 2)

array([[1, 3],
       [5, 7]])

#### Generating Random Numbers

We can create random number arrays from a variety of distribution using NumPy functions and methods.

In [7]:
# creates a random number generator (the seed is for reproducibility)
# np.random.default_rng(seed)
rng = np.random.default_rng()

In [8]:
# return n randoms numbers from a uniform distribution between 0 and 1
# rng.random(n)
rng.random(10)

array([0.39289728, 0.34184962, 0.22906093, 0.15503531, 0.06889173,
       0.68780044, 0.79470652, 0.14627738, 0.25122404, 0.73235496])

In [9]:
# integers(rangeStart, rangeFinish, quantity_of_numbers)
rng.integers(0, 10, 100)

array([2, 5, 0, 0, 0, 1, 4, 1, 0, 9, 7, 0, 3, 0, 2, 7, 5, 9, 2, 2, 5, 8,
       8, 4, 2, 6, 9, 9, 1, 2, 8, 9, 8, 5, 3, 7, 0, 8, 6, 3, 3, 4, 2, 5,
       3, 3, 9, 0, 3, 4, 0, 0, 2, 3, 3, 3, 1, 8, 8, 4, 7, 9, 1, 4, 3, 9,
       9, 1, 8, 1, 6, 3, 8, 7, 8, 9, 7, 4, 0, 7, 8, 8, 4, 4, 3, 9, 2, 2,
       3, 2, 3, 8, 5, 3, 8, 6, 7, 8, 9, 4], dtype=int64)

In [10]:
# return n random number from a normal distribution with a given mean and standard deviation
# rng.normal(mean, stdev, n)
rng = np.random.default_rng()

mean, stddev = 5, 1
random_normal = rng.normal(mean, stddev, size=10)
random_normal

# we are using the normal method on 'rng' to return an array with 10 random numbers from a normal
# distribution with a mean of 5 and a st.deviation of 1

array([4.98961884, 5.36369528, 4.51757429, 3.56661505, 4.94755407,
       4.62355051, 4.23802136, 4.25745236, 4.91413062, 4.45393226])