## Array Functions

Array functions let you perform other aggregations like median and percentiles

In [1]:
import numpy as np

In [2]:
sales = [[0, 5, 155, 0, 518], [0, 1827, 616, 317, 325]]
sales_array = np.array(sales)

sales_array

array([[   0,    5,  155,    0,  518],
       [   0, 1827,  616,  317,  325]])

In [3]:
# np.median(array) - returns the median value in an array
np.median(sales_array)

236.0

In [4]:
# np.percentile(array, n) - returns a value in the nª percentile in an array
np.percentile(sales_array, 90)

737.0999999999996

In [5]:
# np.unique(array) - returns the unique value in an array
np.unique(sales_array)

array([   0,    5,  155,  317,  325,  518,  616, 1827])

In [6]:
price = np.array([2.6, 7.2, 6.92, 3.88, 0.78, 2.67, 8.87, 0.23, 5.23, 6.3])

inventory = np.array([79, 22, 20, 48, 8, 76, 12, 16, 5, 64])

product_value = price * inventory 

product_value.sort()

In [7]:
reshaped_product_value = product_value.reshape(2, 5)
reshaped_product_value

array([[  3.68,   6.24,  26.15, 106.44, 138.4 ],
       [158.4 , 186.24, 202.92, 205.4 , 403.2 ]])

In [8]:
np.median(reshaped_product_value) # função de mediana

148.4

In [9]:
# np.percentile(reshaped_product_value, percentile)
np.percentile(reshaped_product_value, 10) # 10 percentile 

5.984

In [10]:
np.sqrt(reshaped_product_value).round(2) # raiz quadrada de cada valor 

array([[ 1.92,  2.5 ,  5.11, 10.32, 11.76],
       [12.59, 13.65, 14.24, 14.33, 20.08]])

In [11]:
np.unique(reshaped_product_value) # print the array with unique values

array([  3.68,   6.24,  26.15, 106.44, 138.4 , 158.4 , 186.24, 202.92,
       205.4 , 403.2 ])