## Filtering Arrays

We can filter arrays by indexing them with a logical test

* Only the array elements in positions where the logical test returns True are returned

In [2]:
import numpy as np

In [4]:
my_array =np.arange(20)
my_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [5]:
my_array % 2 == 0

array([ True, False,  True, False,  True, False,  True, False,  True,
       False,  True, False,  True, False,  True, False,  True, False,
        True, False])

In [6]:
my_array[my_array % 2 == 0]

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [7]:
even_odd = np.array(['even', 'odd'] * 10)
even_odd

array(['even', 'odd', 'even', 'odd', 'even', 'odd', 'even', 'odd', 'even',
       'odd', 'even', 'odd', 'even', 'odd', 'even', 'odd', 'even', 'odd',
       'even', 'odd'], dtype='<U4')

In [8]:
even_odd != 'odd'

array([ True, False,  True, False,  True, False,  True, False,  True,
       False,  True, False,  True, False,  True, False,  True, False,
        True, False])

In [9]:
even_odd[even_odd != 'odd']

array(['even', 'even', 'even', 'even', 'even', 'even', 'even', 'even',
       'even', 'even'], dtype='<U4')

In [10]:
my_array[my_array % 2 != 0] = 999
my_array

array([  0, 999,   2, 999,   4, 999,   6, 999,   8, 999,  10, 999,  12,
       999,  14, 999,  16, 999,  18, 999])

In [12]:
my_array[even_odd == 'even'] = 0
my_array

array([  0, 999,   0, 999,   0, 999,   0, 999,   0, 999,   0, 999,   0,
       999,   0, 999,   0, 999,   0, 999])

You can filter arrays with multiple logical tests
* Use | for conditions and & for and conditions

In [14]:
mask = (even_odd != 'odd') | (even_odd != 'even')

even_odd[mask]

array(['even', 'odd', 'even', 'odd', 'even', 'odd', 'even', 'odd', 'even',
       'odd', 'even', 'odd', 'even', 'odd', 'even', 'odd', 'even', 'odd',
       'even', 'odd'], dtype='<U4')

In [18]:
my_array[(my_array < 0) | (my_array > 1000)]

array([], dtype=int32)

In [20]:
new_array = np.arange(10)
new_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
new_array[(new_array % 2 == 0) & (new_array > 4)]

array([6, 8])

You can filter arrays based on values in other array

* Use boolean array returned from the other array to index the array which you want to filter.

In [25]:
new_array = np.arange(20)

In [23]:
my_array

array([  0, 999,   0, 999,   0, 999,   0, 999,   0, 999,   0, 999,   0,
       999,   0, 999,   0, 999,   0, 999])

In [27]:
new_array[my_array != 0]

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [28]:
new_array[my_array == 0]

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [29]:
my_array[new_array % 2 == 0]

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])