## Sorting Arrays

The sort() method will sort arrays in place
* Use the axis argument to specify the dimention to sort by

In [1]:
import numpy as np

In [2]:
sales = [[0, 5, 155, 0, 518], [0, 1827, 616, 317, 325]]
sales_array = np.array(sales)

sales_array

array([[   0,    5,  155,    0,  518],
       [   0, 1827,  616,  317,  325]])

In [5]:
sales_array.sort() # axis = 1 by default, which sorts a two-dimensioan larray row by row 
sales_array

array([[   0,    0,    5,  155,  518],
       [   0,  317,  325,  616, 1827]])

In [9]:
sales = [[0, 5, 155, 0, 518], [0, 1827, 616, 317, 325]]
sales_array = np.array(sales)

In [12]:
sales_array.sort(axis=0) # axis = 0 will sort by columns
sales_array

array([[   0,    5,  155,    0,  325],
       [   0, 1827,  616,  317,  518]])

[19, 20, 21, 22, 23, 24, 25]